### ISSUE TITLE
A little detail about the serialization of the image property layout 

### ISSUE THREAD

**Issue by Jamalosur1** [r-aghaei/SharedResourcesExample#1]
Hello good job, if the two projects are in the same solution it works fine.

However, if the resources project is not in the solution and only the reference is added, when copying and pasting controls, the image property is serialized incorrectly and the resources are copied locally in the form's resource file.

Greetings

**Comment by r-aghaei** [comment]
@Jamalosur1 Thanks. It's expected behavior and the solution relies on the fact that the projects are in the same projects.
